<a href="https://colab.research.google.com/github/Riz08/My-python-practice-repo/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#array creation

list1=[1,2,3,4]
list2=[5,6,7,8]

print(type(list1))

import numpy as np

a= np.array(list1)
print(a)
print(type(a))

b= np.array(list2)
print(b)
print(type(b))


<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>
[5 6 7 8]
<class 'numpy.ndarray'>


In [27]:

#array makes all data same type
#here in a we have string float and int. It makes all str
#here in b we have  float and int. It makes all values float
#1 dimensional
a=np.array([8,3.25,"Riza",5,9,3.14])
print(type(a))
print(a)
print(a.dtype)

#2 dimensional
b=np.array([[1,2,3],[4,5,6]])
print(type(b))
print(b)
print(b.dtype)


<class 'numpy.ndarray'>
['8' '3.25' 'Riza' '5' '9' '3.14']
<U32
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
int64


In [33]:
#size of the array
print(b.size)
#shape of array
print(b.shape)
#itemsize of array
print(a.itemsize)
#indexing
print(b[1][1:])
print(a[0: :2])
#dimention check
print(b.ndim)



6
(2, 3)
128
[5 6]
['8' 'Riza' '9']
2


In [43]:
#to gey desired dimension

a=np.array([4,7,10,13,12,14,15], ndmin=6)
print(a)

[[[[[[ 4  7 10 13 12 14 15]]]]]]


In [59]:
#automatic creation of array
#arange
#numpy.arange([start, ],stop,[step, )]dtype=None, *, like=None)


a=np.arange(9,35,2, dtype=float)
print(a)

#how to change dimension using reshape
b=np.arange(9).reshape(3,3)
print(b)


[ 9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33.]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [72]:
#np.linspace is used to automatically create equally spaced intervals
#np.linspace(start,end,space number, endpoint=False, retstep=True)
a=np.linspace(1,5,num=10,endpoint=False, retstep=True) #endpoint will take last value out of calculation #retstep is gap value between numbers
print(a)

























(array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6]), 0.4)
