<a href="https://colab.research.google.com/github/Riz08/My-python-practice-repo/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#array creation

list1=[1,2,3,4]
list2=[5,6,7,8]

print(type(list1))

import numpy as np

a= np.array(list1)
print(a)
print(type(a))

b= np.array(list2)
print(b)
print(type(b))


<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>
[5 6 7 8]
<class 'numpy.ndarray'>


In [ ]:

#array makes all data same type
#here in a we have string float and int. It makes all str
#here in b we have  float and int. It makes all values float
#1 dimensional
a=np.array([8,3.25,"Riza",5,9,3.14])
print(type(a))
print(a)
print(a.dtype)

#2 dimensional
b=np.array([[1,2,3],[4,5,6]])
print(type(b))
print(b)
print(b.dtype)


<class 'numpy.ndarray'>
['8' '3.25' 'Riza' '5' '9' '3.14']
<U32
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
int64


In [ ]:
#size of the array
print(b.size)
#shape of array
print(b.shape)
#itemsize of array
print(a.itemsize)
#indexing
print(b[1][1:])
print(a[0: :2])
#dimention check
print(b.ndim)



6
(2, 3)
128
[5 6]
['8' 'Riza' '9']
2


In [ ]:
#to gey desired dimension

a=np.array([4,7,10,13,12,14,15], ndmin=6)
print(a)

[[[[[[ 4  7 10 13 12 14 15]]]]]]


In [ ]:
#automatic creation of array
#arange
#numpy.arange([start, ],stop,[step, )]dtype=None, *, like=None)


a=np.arange(9,35,2, dtype=float)
print(a)

#how to change dimension using reshape
b=np.arange(9).reshape(3,3)
print(b)


[ 9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33.]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#np.linspace is used to automatically create equally spaced intervals
#np.linspace(start,end,space number, endpoint=False, retstep=True)
a=np.linspace(1,5,num=10,endpoint=False, retstep=True) #endpoint will take last value out of calculation #retstep true is equal is gap value between numbers
print(a)


(array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6]), 0.4)


In [ ]:
#np.eye(N, M=None, k=0, dtype=float, order='C', *, like=None)
#order C means row wise and F means column wise
"""N : int Number of rows in the output.
M : int, optional Number of columns in the output. If None, defaults to N.
k : int, optionalIndex of the diagonal: 0 (the default) refers to the main diagonal,
a positive value refers to an upper diagonal, and a negative value
to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
column-major (Fortran-style) order in memory."""

a=np.eye(3,3) #identity matriz is a diagonal shape
print(a)

a=np.eye(3,3,k=1)  #k=1 value changes the position of the diagonal to the right by 1 step
print(a)

a=np.eye(3,3,k=-1)   #k=1 value changes the position of the diagonal to the left by 1 step
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
#np.zeros if under 18 ages are not allowed to drint we can put all lages below 18 as zeros array
#np.ones if over 18 ages are allowed to drint we can put all ages over 18 as ones array


a= np.zeros((3,2))
print(a)

a= np.ones((5))
print(a)


[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1. 1. 1. 1.]


<function numpy.ones>

In [ ]:
#np.full is used to return a new shape of array with predefined value
b=["Riza","Fahima"]

a=np.full((3,3),[1,b[0],b[1]], order="F") #F should fill in coloumn the values
print(a)

a=np.full((3,2),np.inf)
print(a)








[['1' 'Riza' 'Fahima']
 ['1' 'Riza' 'Fahima']
 ['1' 'Riza' 'Fahima']]
[[inf inf]
 [inf inf]
 [inf inf]]


In [ ]:
#transpose changes the row to column and coloumn to row

a=np.arange(10).reshape(2,5)
b=np.transpose(a) #both ways are same to transpose
c=b.T
d=b.reshape(2,5,1) #3dimensional array #make sure the reshape multiplication is equals to number of elements (2*5*1=10=number of elements)

print(a)
print(b)
print(c)
print(d)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[0]
  [5]
  [1]
  [6]
  [2]]

 [[7]
  [3]
  [8]
  [4]
  [9]]]


In [ ]:
#flatten makes 2 dimensional or 3 dimensional data in single dimensional

a=np.arange(4).reshape(2,2)
print(a)
b=a.flatten()  #no use of np
print(b)

b[0]=12
print(b) #it only changes the value of b but not for a
print(a)


[[0 1]
 [2 3]]
[0 1 2 3]
[12  1  2  3]
[[0 1]
 [2 3]]


In [ ]:
#ravel same as flatten with one small difference

a=np.arange(4).reshape(2,2)
print(a)
b=a.ravel()  #no use of np
print(b)

b[0]=12
print(b) #it changes the value of b and a both with changes made in b indexing
print(a)

[[0 1]
 [2 3]]
[0 1 2 3]
[12  1  2  3]
[[12  1]
 [ 2  3]]


In [ ]:
#concatenate joins arrays

a=np.arange(4).reshape(2,2)
b=np.arange(5,9).reshape(2,2)
c=np.concatenate((a,b),axis=None)
d=np.concatenate((a,b),axis=1)

print(a)
print(b)
print(c)
print(d)



[[0 1]
 [2 3]]
[[5 6]
 [7 8]]
[0 1 2 3 5 6 7 8]
[[0 1 5 6]
 [2 3 7 8]]


In [ ]:
#vstack shows arrays in vertical order and hstack shows horizontally

a=np.arange(4).reshape(2,2)
b=np.arange(5,9).reshape(2,2)
c=np.vstack((a,b))
d=np.hstack((a,b))
print(a)
print(b)
print(c)
print(d)

[[0 1]
 [2 3]]
[[5 6]
 [7 8]]
[[0 1]
 [2 3]
 [5 6]
 [7 8]]
[[0 1 5 6]
 [2 3 7 8]]


In [ ]:
#np.split splits arrays

a=np.arange(9)
b=np.split(a,3)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [1]:
#np.insert enables us to insert data axis wise
#Np.delete enables us to delete element axis wise
#np.insert(arr, obj, values, axis=None)
#Axis =0 means row wise insert and axis=1 means coloumn wise insert,axis=None will flatten the matrix
#obj is which posiiton to input


import numpy as np 
a=np.arange(4).reshape(2,2)
b=np.insert(a,1,(12,13),axis=0)
c=np.insert(a,1,(12,13),axis=1)
d=np.insert(a,1,(12,13),axis=None)
e=np.delete(c,1,axis=1)

print(b)
print(c)
print(d)
print(e)

[[ 0  1]
 [12 13]
 [ 2  3]]
[[ 0 12  1]
 [ 2 13  3]]
[ 0 12 13  1  2  3]
[[0 1]
 [2 3]]
